steps:
# Applying all the migrations for 'database_01'
- name: gcr.io/cloud-builders/docker
  waitFor: ['-']
  id: 'Apply Flyway Migrations'
  entrypoint: bash
  args:
  - -c
  - |
    docker run \
    -v $(pwd)/src/test/resources/migrations/database_01:/flyway/sql \
    -e FLYWAY_USER=${_FLYWAY_USER} \
    -e FLYWAY_PASSWORD=${_FLYWAY_PASSWORD} \
    -e FLYWAY_URL=${_FLYWAY_URL} \
    -e FLYWAY_LOCATIONS=filesystem:/flyway/sql \
    flyway/flyway:11.3 migrate

options:
  logging: CLOUD_LOGGING_ONLY
